Fix undefined reference to list_* funcs when srcdir != builddir
distcheck still doesn't pass, but I think that's because
tests are being run for libraries that we don't build.